

module Javalette.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program = Pdefs [Def]
  deriving (Eq, Ord, Show, Read)

data Def = DFun Type Ident [Arg] [Stm]
  deriving (Eq, Ord, Show, Read)

data Arg = ADecl Type Ident
  deriving (Eq, Ord, Show, Read)

data Stm
    = Empty
    | SBlock [Stm]
    | SDecls Type [Item]
    | SAss Ident Exp
    | SIncr Ident
    | SDecr Ident
    | SReturn Exp
    | SNoReturn
    | SIf Exp Stm
    | SIfElse Exp Stm Stm
    | SWhile Exp Stm
    | SExp Exp
  deriving (Eq, Ord, Show, Read)

data Item = NoInit Ident | Init Ident Exp
  deriving (Eq, Ord, Show, Read)

data Type = Int | Double | Bool | Void | Fun Type [Type]
  deriving (Eq, Ord, Show, Read)

data Exp
    = EId Ident
    | EInt Integer
    | EDouble Double
    | ETrue
    | EFalse
    | EApp Ident [Exp]
    | EString String
    | ENeg Exp
    | ENot Exp
    | EMul Exp MulOp Exp
    | EAdd Exp AddOp Exp
    | ECmp Exp CmpOp Exp
    | EAnd Exp Exp
    | EOr Exp Exp
  deriving (Eq, Ord, Show, Read)

data AddOp = OPlus | OMinus
  deriving (Eq, Ord, Show, Read)

data MulOp = OTimes | ODiv | OMod
  deriving (Eq, Ord, Show, Read)

data CmpOp = OLt | OLtEq | OGt | OGtEq | OEq | ONEq
  deriving (Eq, Ord, Show, Read)

